name: Format
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE.txt'
  pull_request:
    paths-ignore:
      - 'LICENSE.txt'
jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
