name: 🚀
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  rubygems:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-24.04

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    # https://github.com/kachick/rspec-matchers-power_assert_matchers/deployments/release
    # https://github.com/kachick/rspec-matchers-power_assert_matchers/settings/environments
    environment: release

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: rubygems/release-gem@v1
